### ISSUE TITLE
ZLXQ.py

### ISSUE THREAD

**Issue by kuake0** [wangquanfugui233/Bilibili_Python#14]
不知道什么原因运行不了这个脚本，其他脚本正常运行

Traceback (most recent call last):
  File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/ZLXQ.py", line 320, in <module>
    zlxq.run()
  File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/ZLXQ.py", line 298, in run
    cookies = self.fetch_cookie()
  File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/ZLXQ.py", line 57, in fetch_cookie
    cookie = cookies.split("@")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by wangquanfugui233** [comment]
这个不是给你们用的，可以删的
