### ISSUE TITLE
Bilibili_Prize.py消息推送报错

### ISSUE THREAD

**Issue by ALin596** [wangquanfugui233/Bilibili_Python#17]
老哥帮忙看看是什么原因导致的。
```
**********丿阿林**********
当前经验值：12092
当前硬币数：182.2，下一等级升级天数约257
恭喜你中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈
中将时间是：2022-07-14 11:43:40
检查白名单
已存在于白名单
Bilibili天选时刻通知

详细信息:
中将时间：【2022-07-14 11:43:40】 今天的天选中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈


gotify 服务启动
Exception in thread gotify:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='47.103.127.79', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/notify.py", line 216, in gotify
    response = requests.post(url,data=data).json()
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='47.103.127.79', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))

## 执行结束... 2022-07-14 15:25:19 耗时 3 秒
```

**Comment by ALin596** [comment]
> 老哥帮忙看看是什么原因导致的。
> 
> ```
> **********丿阿林**********
> 当前经验值：12092
> 当前硬币数：182.2，下一等级升级天数约257
> 恭喜你中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈
> 中将时间是：2022-07-14 11:43:40
> 检查白名单
> 已存在于白名单
> Bilibili天选时刻通知
> 
> 详细信息:
> 中将时间：【2022-07-14 11:43:40】 今天的天选中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈
> 
> 
> gotify 服务启动
> Exception in thread gotify:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
>     raise err
>   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/usr/lib/python3.9/http/client.py", line 1279, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.9/http/client.py", line 974, in send
>     self.connect()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='我的服务器ip', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/notify.py", line 216, in gotify
>     response = requests.post(url,data=data).json()
>   File "/usr/lib/python3.9/site-packages/requests/api.py", line 117, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='我的服务器ip', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> ## 执行结束... 2022-07-14 15:25:19 耗时 3 秒
> ```

**Comment by wangquanfugui233** [comment]
这个好像是它notify的问题，不是我的问题我只是调用它而已

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月14日 15:28
主题: [wangquanfugui233/Bilibili_Python] Bilibili_Prize.py消息推送报错 (Issue #17)


老哥帮忙看看是什么原因导致的。

**********丿阿林**********



当前经验值：12092



当前硬币数：182.2，下一等级升级天数约257



恭喜你中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈



中将时间是：2022-07-14 11:43:40



检查白名单



已存在于白名单



Bilibili天选时刻通知







详细信息:



中将时间：【2022-07-14 11:43:40】 今天的天选中奖，奖品是：100崩坏3水晶 --- 兑奖up主是：忘忧甜甜圈











gotify 服务启动



Exception in thread gotify:



Traceback (most recent call last):



  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn



    conn = connection.create_connection(



  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection



    raise err



  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection



    sock.connect(sa)



ConnectionRefusedError: [Errno 111] Connection refused







During handling of the above exception, another exception occurred:







Traceback (most recent call last):



  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen



    httplib_response = self._make_request(



  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request



    conn.request(method, url, **httplib_request_kw)



  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request



    super(HTTPConnection, self).request(method, url, body=body, headers=headers)



  File "/usr/lib/python3.9/http/client.py", line 1279, in request



    self._send_request(method, url, body, headers, encode_chunked)



  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request



    self.endheaders(body, encode_chunked=encode_chunked)



  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders



    self._send_output(message_body, encode_chunked=encode_chunked)



  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output



    self.send(msg)



  File "/usr/lib/python3.9/http/client.py", line 974, in send



    self.connect()



  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect



    conn = self._new_conn()



  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn



    raise NewConnectionError(



urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused







During handling of the above exception, another exception occurred:







Traceback (most recent call last):



  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send



    resp = conn.urlopen(



  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen



    retries = retries.increment(



  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment



    raise MaxRetryError(_pool, url, error or ResponseError(cause))



urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='47.103.127.79', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))







During handling of the above exception, another exception occurred:







Traceback (most recent call last):



  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner



    self.run()



  File "/usr/lib/python3.9/threading.py", line 910, in run



    self._target(*self._args, **self._kwargs)



  File "/ql/data/scripts/wangquanfugui233_Bilibili_Python/notify.py", line 216, in gotify



    response = requests.post(url,data=data).json()



  File "/usr/lib/python3.9/site-packages/requests/api.py", line 117, in post



    return request('post', url, data=data, json=json, **kwargs)



  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request



    return session.request(method=method, url=url, **kwargs)



  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request



    resp = self.send(prep, **send_kwargs)



  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send



    r = adapter.send(request, **kwargs)



  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send



    raise ConnectionError(e, request=request)



requests.exceptions.ConnectionError: HTTPConnectionPool(host='47.103.127.79', port=5701): Max retries exceeded with url: /message?token=FJ0_uLwDoPCw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e771cbee0>: Failed to establish a new connection: [Errno 111] Connection refused'))







## 执行结束... 2022-07-14 15:25:19 耗时 3 秒



―
